### ISSUE TITLE
include standard CSS

### ISSUE THREAD

**Issue by jakecraige** [poetic/ember-cli-panels#7]
Include some standard CSS for the panes to make things like draggable work properly. A current demo app i'm working on looks like

```scss
.ps-panel {
  position: relative;
}

.ps-pane {
  overflow-x: hidden;
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
  height: 700px; // ideally we can make this dynamic
  margin: 0;
  padding: 0;
  float: left;
  display: block;
  width: 100%;
}

$height: 3rem;

.ps-pane-menu {
  background: $black;
  height: $height;
  overflow: hidden;
  text-align: justify;
  white-space: nowrap;
}


.ps-pane-link {
  line-height: 1rem;
  color: $transparent-white;
  text-decoration: none;
  font-size: 1.0rem;
  padding: 1rem 2rem;
  display: inline-block;

  &.active {
    color: $white;
  }
}
```
